import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

decorations = "Buttonless"

opacity = 0.7
#blur = true

option_as_alt = "Both"

[font]
size = 12.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "Cascadia Code"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "MesloLGS Nerd Font Mono"
family = "Cascadia Code"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "Cascadia Code"
style = "Regular"

[cursor]
style = { shape = "Block", blinking = "On" }
