import = [
    "~/.config/alacritty/themes/themes/cyberdream.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
size = 12.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Regular"
